# configuration for "master" branch
-
  branches:
    only:
      - master
  configuration: Release
  before_build:
    - ps: nuget restore .\src\SImpl.Stack.sln
  build:
    publish_nuget: true
    project: .\src\SImpl.Stack.sln
  
  deploy:
    provider: NuGet
    api_key:
      secure: /NnwbJeEjsuDddacYwWI7cJYsA+9HaBFJGbIyAO+/ykUxod9O/kPOGHRdk+CLuhq
    skip_symbols: false
    artifact: /.*(\.|\.s)nupkg/
