# configuration for "master" branch
-
  branches:
    only:
      - master
      - v2/master
  configuration: Release
  environment:
    DOTNET_NOLOGO: 1
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  image: Visual Studio 2022
  install:
    - ps: |
        Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
        & $env:temp\dotnet-install.ps1 -Architecture x64 -Version '10.0.100' -InstallDir "$env:ProgramFiles\dotnet"
  before_build:
    - cmd: dotnet restore .\src\SImpl.Stack.slnx
  build:
    publish_nuget: false
    project: .\src\SImpl.Stack.slnx
  after_build:
    - cmd: dotnet pack src\SImpl.Stack.slnx -c Release --no-build -o artifacts
  artifacts:
    - path: artifacts\*.nupkg
  deploy:
    provider: NuGet
    api_key:
      secure: WTf+t9lyREu2uEik7ORDYCAjnZkvRiKRRaS/DrxrDucL2QsvkYRUXxHzin5B8MkD
    skip_symbols: false
    artifact: /.*(\.|\.s)nupkg/
