<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SImpl.CQRS.Commands\SImpl.CQRS.Commands.csproj" />
    <ProjectReference Include="..\SImpl.CQRS.Events\SImpl.CQRS.Events.csproj" />
    <ProjectReference Include="..\SImpl.Hosts.WebHost\SImpl.Hosts.WebHost.csproj" />
    <ProjectReference Include="..\SImpl.Messaging.CQRS\SImpl.Messaging.CQRS.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Polly" />
    <PackageReference Include="Rebus" />
    <PackageReference Include="Rebus.OpenTelemetry" />
    <PackageReference Include="Rebus.ServiceProvider" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

</Project>
