<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <AssemblyName>SImpl.OAuth</AssemblyName>
        <RootNamespace>SImpl.OAuth</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Portable.BouncyCastle" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SImpl\SImpl.csproj" />
    </ItemGroup>

</Project>
