<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Dapper.Transaction" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="System.Configuration.ConfigurationManager"/>
    <PackageReference Include="System.Data.SqlClient" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SImpl.Storage.Repository\SImpl.Storage.Repository.csproj" />
  </ItemGroup>

</Project>
