<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <Authors>Arkadiusz Biel</Authors>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SImpl\SImpl.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Scrutor" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    </ItemGroup>
    
</Project>
