<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>SImpl.Http.OAuth</RootNamespace>
        <IsPackable>true</IsPackable>
        <PackageId>SImpl.Http.OAuth</PackageId>
        <AssemblyName>SImpl.Http.OAuth</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SImpl.DependencyInjection\SImpl.DependencyInjection.csproj" />
      <ProjectReference Include="..\SImpl.OAuth\SImpl.OAuth.csproj" />
    </ItemGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
      <PackageReference Include="Newtonsoft.Json" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="AspNetCore" />
    </ItemGroup>

</Project>
